development:
  adapter: postgresql
  encoding: unicode
  database: link_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: link_test
  pool: 5
  username:
  password:

